server:
    port: 8083

spring:
#    profiles:
#        active: dev
    application:
        name: gateway
#    cloud:
#        config:
#            uri: http://admin:admin@localhost:8761
#            profile: dev
##        bootstrap:
#            enables: false

eureka:
    instance:
        prefer-ip-address: true
    client:
        serviceUrl:
#            defaultZone: http://admin:admin@localhost:8761/eureka/
            defaultZone: http://admin:admin@localhost:8761/eureka/



zuul:
    routes:
        config-client:
            path: /client/**
            service-id: config-client
#ribbon:
#      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule # 配置服务端负载均衡策略

#ribbon:
#    eureka:
#        enabled: false